// Configuration file for production environment
// Auto-generated by build-config.js

// Check if config already exists to prevent duplicate declaration
if (typeof window !== 'undefined' && window.config) {
    console.log('Config already loaded, skipping...');
} else {
    const config = {
        // Stripe Configuration
        stripe: {
            publishableKey: 'pk_live_51Rolv8I5JHWOZqzkQzDNnxsFw1q350Kqu0OdLBM9G1XKuhSXclErAds7w2qZ9g4HvUjqTnu2vVXI8vdNhLUBX9Dn00Y8s2BKkU',
            priceIds: {
                proMonthly: 'price_1RqwlBI5JHWOZqzkNDhcorZk'
            }
        },
        
        // Google Analytics
        analytics: {
            measurementId: 'G-BNQRGZZEHK'
        },
        
        // API Endpoints
        api: {
            baseUrl: 'https://ai-assistant-hub-app.azurewebsites.net',
            billingEndpoint: '/api/billing/create-checkout-session'
        },
        
        // Website Configuration
        website: {
            domain: 'https://myassistanthub.com',
            supportEmail: 'support@myassistanthub.com'
        }
    };

    // Export for use in other scripts
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = config;
    } else {
        window.config = config;
    }
}

// Force cache bust: Sat Aug  2 22:02:12 CDT 2025
