// Configuration file for production environment
// Auto-generated by build-config.js

const config = {
    // Stripe Configuration
    stripe: {
        publishableKey: 'pk_live_51Rolv8I5JHWOZqzkQzDNnxsFw1q350Kqu0OdLBM9G1XKuhSXclErAds7w2qZ9g4HvUjqTnu2vVXI8vdNhLUBX9Dn00Y8s2BKkU',
        priceIds: {
            proMonthly: 'price_1RpK6CI5JHWOZqzkceD9ddtl'
        }
    },
    
    // Google Analytics
    analytics: {
        measurementId: 'G-BNQRGZZEHK'
    },
    
    // API Endpoints
    api: {
        baseUrl: 'https://myassistanthub.com',
        billingEndpoint: '/api/billing/create-checkout-session'
    },
    
    // Website Configuration
    website: {
        domain: 'https://myassistanthub.com',
        supportEmail: 'support@myassistanthub.com'
    }
};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = config;
} else {
    window.config = config;
}
