#!/usr/bin/env node

// Build script to replace configuration values based on environment variables
// Usage: node build-config.js [environment]

const fs = require('fs');
const path = require('path');

const environment = process.argv[2] || 'production';

// Configuration for different environments
const configs = {
    development: {
        stripe: {
            publishableKey: 'pk_test_your_test_key_here',
            priceIds: {
                proMonthly: 'price_test_monthly',
                proYearly: 'price_test_yearly'
            }
        },
        analytics: {
            measurementId: 'G-TEST123456'
        },
        api: {
            baseUrl: 'http://localhost:3000',
            billingEndpoint: '/api/billing/create-checkout-session'
        },
        website: {
            domain: 'http://localhost:8080',
            supportEmail: 'dev@example.com'
        }
    },
    production: {
        stripe: {
            publishableKey: process.env.STRIPE_PUBLISHABLE_KEY || 'pk_test_your_test_key_here',
            priceIds: {
                proMonthly: 'price_1RqwlBI5JHWOZqzkNDhcorZk'
            }
        },
        analytics: {
            measurementId: 'G-BNQRGZZEHK'
        },
        api: {
            baseUrl: 'https://ai-assistant-hub-app.azurewebsites.net',
            billingEndpoint: '/api/billing/create-checkout-session'
        },
        website: {
            domain: 'https://myassistanthub.com',
            supportEmail: 'support@myassistanthub.com'
        }
    }
};

const config = configs[environment];

if (!config) {
    console.error(`Unknown environment: ${environment}`);
    console.log('Available environments:', Object.keys(configs).join(', '));
    process.exit(1);
}

// Generate the config.js content
const configContent = `// Configuration file for ${environment} environment
// Auto-generated by build-config.js

const config = {
    // Stripe Configuration
    stripe: {
        publishableKey: '${config.stripe.publishableKey}',
        priceIds: {
            proMonthly: '${config.stripe.priceIds.proMonthly}'
        }
    },
    
    // Google Analytics
    analytics: {
        measurementId: '${config.analytics.measurementId}'
    },
    
    // API Endpoints
    api: {
        baseUrl: '${config.api.baseUrl}',
        billingEndpoint: '${config.api.billingEndpoint}'
    },
    
    // Website Configuration
    website: {
        domain: '${config.website.domain}',
        supportEmail: '${config.website.supportEmail}'
    }
};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = config;
} else {
    window.config = config;
}
`;

// Write the config file
fs.writeFileSync(path.join(__dirname, 'config.js'), configContent);

console.log(`✅ Configuration generated for ${environment} environment`);
console.log(`📁 Config file: ${path.join(__dirname, 'config.js')}`);
console.log(`🔑 Stripe Key: ${config.stripe.publishableKey.substring(0, 20)}...`);
console.log(`📊 Analytics ID: ${config.analytics.measurementId}`);
console.log(`🌐 API Base URL: ${config.api.baseUrl}`); 