// Configuration file for production environment
// Auto-generated by build-config.js

const config = {
    // Stripe Configuration
    stripe: {
        publishableKey: 'pk_test_your_test_key_here',
        priceIds: {
            proMonthly: 'price_1RpKAYI5JHWOZqzklUS9vUna'
        }
    },
    
    // Google Analytics
    analytics: {
        measurementId: 'G-BNQRGZZEHK'
    },
    
    // API Endpoints
    api: {
        baseUrl: 'https://ai-assistant-hub-app.azurewebsites.net',
        billingEndpoint: '/api/billing/create-checkout-session'
    },
    
    // Website Configuration
    website: {
        domain: 'https://myassistanthub.com',
        supportEmail: 'support@myassistanthub.com'
    }
};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = config;
} else {
    window.config = config;
}
