# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ai-assistant-hub-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Add artifact retention to automatically clean up old artifacts
env:
  ARTIFACT_RETENTION_DAYS: 1  # Keep artifacts for only 1 day

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create deployment package
        run: |
          # Create a clean deployment directory with only necessary files
          mkdir -p deploy-package
          
          # Copy website files for static hosting
          cp -r website/ deploy-package/
          
          # Copy server files for backend functionality
          cp -r server/ deploy-package/
          
          # Copy package files
          cp -r package*.json deploy-package/ 2>/dev/null || true
          cp -r .env* deploy-package/ 2>/dev/null || true
          
          # Remove unnecessary files to reduce size
          find deploy-package -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true
          find deploy-package -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true
          find deploy-package -name ".DS_Store" -type f -delete 2>/dev/null || true
          find deploy-package -name "*.log" -type f -delete 2>/dev/null || true
          find deploy-package -name "*.zip" -type f -delete 2>/dev/null || true
          
          echo "Deployment package created successfully"
          du -sh deploy-package/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy-package/
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9DF71466FB354561B5F79F785FA1C4BC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C079B312C21F4F37A113AC41E1E1342C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_67DD3F6FD8B94A69A54365A530866644 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ai-assistant-hub-app'
          slot-name: 'Production'
          package: .
          